spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root:  trace
