app:
  jwt:
    secret: "hoge"
    expiration-time: 3600
    issuer: "https://hoge.com"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://www.googleapis.com/oauth2/v3/certs"
          issuer-uri: "https://accounts.google.com"
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root:  trace
